# Generated by Django 2.1.dev20180105000746 on 2019-05-13 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='description',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='document',
            name='document',
        ),
        migrations.RemoveField(
            model_name='document',
            name='uploaded_at',
        ),
    ]
