# Generated by Django 2.1.dev20180105000746 on 2019-05-13 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190513_0105'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientsInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.RenameModel(
            old_name='Document',
            new_name='Campaign',
        ),
        migrations.AddField(
            model_name='clientsinfo',
            name='campaign',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Campaign'),
        ),
    ]
