# Generated by Django 2.1.dev20180105000746 on 2019-05-13 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20190513_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientsinfo',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='clientsinfo',
            name='lastName',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='clientsinfo',
            name='phoneNumber',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
