# Generated by Django 2.1.dev20180105000746 on 2019-05-15 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20190513_1540'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableColumns',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Temp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('columnName', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
