# Generated by Django 2.1.dev20180105000746 on 2019-05-15 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_tablecolumns_temp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='temp',
            name='columnName',
        ),
        migrations.AddField(
            model_name='temp',
            name='URL',
            field=models.FileField(default=None, upload_to='documents/'),
        ),
        migrations.AddField(
            model_name='temp',
            name='name',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
