# Generated by Django 2.1.dev20180105000746 on 2019-05-16 02:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20190515_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='temp',
            name='campaign',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Campaign'),
        ),
    ]
